version: '3'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_DATABASE: usuarios
        ports:
            - 62757:27017

        hostname: mongo_db
    mongo_api:
        image: mongo_api
        container_name: mongo_api
        restart: always
        ports:
            - 3000:3000
        environment:
            DB_HOST: mongodb://mongo_db:27017/usuarios  
        volumes:
          - ./data:/data/db
    mongo_web:
        image: mongo_web
        container_name: mongo_web
        restart: always
        ports:
            - 80:80
    
  
        